import Head from 'next/head'
import styles from '../styles/Home.module.css'
import dynamic from 'next/dynamic'
import { Suspense } from 'react'
import "bootstrap/dist/css/bootstrap.css"
import { useEffect } from 'react'
import Products from '../public/products'
import Stories from './components/stories'
import Image from 'next/image'

export default function Home() {

  useEffect(()=>{
    import("bootstrap/dist/js/bootstrap");
  },[])
  
  const Nav = dynamic(() => import('./components/navigation'), {
    suspense: true,
  })
  
  return (
    <div className={styles.container}>    
   
      <Head>
        <title></title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Suspense fallback={`Loading...`}>
      <Nav/>
      </Suspense>
    <Stories/>
    <Products/>
    <Products/>
    <div>
    <Image className="mx-3 rounded border border-danger" src="/images/127.jpg"  width={622} height={555} />
    <Image className="mx-3 rounded border border-danger" src="/images/124.jpg" width={622} height={555} />
    </div>
    <Products/>
    <Products/>
    <Products/>
    <div>
    <Image className="mx-3 rounded border border-danger" src="/images/129.jpg"  width={622} height={555} />
    <Image className="mx-3 rounded border border-danger" src="/images/126.jpg" width={622} height={555} />
    </div>
    <Products/>
    <Products/>
    <Products/>
    <Products/>
    <Products/>
      
    <div>
    <Image className="mx-3 rounded border border-danger" src="/images/125.jpg"  width={622} height={555} />
    <Image className="mx-3 rounded border border-danger" src="/images/127.jpg" width={622} height={555} />
    </div>
    <Products/>
    <Products/>
    <Products/>


    <footer className={styles.footer}>
<h1 style={{fontFamily:'Tanha'}}>
یک خرید لذت بخش
</h1>
      </footer>
    </div>
  )
}




{/*

<main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
*/}